import { describe, expect, it } from "vitest";
import {
  parseBilibiliPageData,
  parseBilibiliSubtitle,
  parseYouTubePlayerResponse,
  parseYouTubeTimedText,
} from "../src/adapters/parsers";

describe("YouTube adapter parsing", () => {
  it("extracts video metadata and available caption tracks", () => {
    const parsed = parseYouTubePlayerResponse({
      videoDetails: { videoId: "abc123", title: "TypeScript course", lengthSeconds: "120" },
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [{
            baseUrl: "https://www.youtube.com/api/timedtext?v=abc123&lang=en",
            languageCode: "en",
            kind: "asr",
            name: { simpleText: "English (auto-generated)" },
          }],
        },
      },
    }, "https://www.youtube.com/watch?v=abc123");

    expect(parsed.video).toEqual({
      platform: "YOUTUBE",
      sourceId: "abc123",
      sourceUrl: "https://www.youtube.com/watch?v=abc123",
      title: "TypeScript course",
      durationMs: 120_000,
    });
    expect(parsed.tracks).toEqual([{ id: "https://www.youtube.com/api/timedtext?v=abc123&lang=en", label: "English (auto-generated)", language: "en", isAutoGenerated: true }]);
  });

  it("normalizes json3 timed text events and ignores empty events", () => {
    expect(parseYouTubeTimedText({ events: [
      { tStartMs: 0, dDurationMs: 1_200, segs: [{ utf8: "Hello " }, { utf8: "world" }] },
      { tStartMs: 1_200, dDurationMs: 300, segs: [{ utf8: "\n" }] },
    ] })).toEqual([{ startMs: 0, endMs: 1_200, text: "Hello world", sourceIndex: 0 }]);
  });
});

describe("Bilibili adapter parsing", () => {
  it("extracts page metadata and makes protocol-relative subtitle URLs usable", () => {
    const parsed = parseBilibiliPageData({
      state: { videoData: { bvid: "BV1xx", title: "数据库课程", duration: 90 } },
      playInfo: { data: { subtitle: { subtitles: [{ id: 7, lan: "zh-CN", lan_doc: "中文", subtitle_url: "//i0.hdslb.com/subtitle.json", type: 0 }] } } },
    }, "https://www.bilibili.com/video/BV1xx");

    expect(parsed.video).toEqual({ platform: "BILIBILI", sourceId: "BV1xx", sourceUrl: "https://www.bilibili.com/video/BV1xx", title: "数据库课程", durationMs: 90_000 });
    expect(parsed.tracks).toEqual([{ id: "https://i0.hdslb.com/subtitle.json", label: "中文", language: "zh-CN", isAutoGenerated: false }]);
  });

  it("converts subtitle seconds to normalized millisecond segments", () => {
    expect(parseBilibiliSubtitle({ body: [
      { from: 1.25, to: 3.5, content: "第一段" },
      { from: 3.5, to: 5, content: "第二段" },
    ] })).toEqual([
      { startMs: 1_250, endMs: 3_500, text: "第一段", sourceIndex: 0 },
      { startMs: 3_500, endMs: 5_000, text: "第二段", sourceIndex: 1 },
    ]);
  });
});
