import { z } from "zod";

export const platformSchema = z.enum(["YOUTUBE", "BILIBILI"]);
export const acquisitionMethodSchema = z.enum(["CAPTION", "TAB_AUDIO"]);
export const taskStatusSchema = z.enum([
  "CREATED",
  "CAPTURING",
  "UPLOADING",
  "PROCESSING",
  "READY",
  "FAILED",
  "CANCELED",
]);
export const documentTemplateSchema = z.enum(["STRUCTURED_NOTES", "ARTICLE"]);
export const outputLanguageSchema = z.enum(["ZH_CN", "SOURCE"]);

export const transcriptSegmentSchema = z.object({
  startMs: z.number().int().nonnegative(),
  endMs: z.number().int().positive(),
  text: z.string().trim().min(1),
  sourceIndex: z.number().int().nonnegative(),
}).refine((value) => value.endMs > value.startMs, {
  message: "endMs must be greater than startMs",
  path: ["endMs"],
});

export const createCaptureSchema = z.object({
  platform: platformSchema,
  acquisitionMethod: acquisitionMethodSchema,
  sourceId: z.string().trim().min(1).max(200),
  sourceUrl: z.string().url(),
  title: z.string().trim().min(1).max(500),
  durationMs: z.number().int().positive().max(3_600_000),
});

export const subtitleSubmissionSchema = z.object({
  language: z.string().trim().min(2).max(35),
  segments: z.array(transcriptSegmentSchema).min(1).max(100_000),
});

export const documentSectionSchema = z.object({
  heading: z.string().trim().min(1).max(300),
  body: z.string().trim().min(1),
  startMs: z.number().int().nonnegative(),
});

export const documentPayloadSchema = z.object({
  title: z.string().trim().min(1).max(500),
  summary: z.string().trim().min(1),
  sections: z.array(documentSectionSchema).min(1).max(100),
});

export const generateDocumentSchema = z.object({
  template: documentTemplateSchema,
  outputLanguage: outputLanguageSchema,
});

export type Platform = z.infer<typeof platformSchema>;
export type AcquisitionMethod = z.infer<typeof acquisitionMethodSchema>;
export type TaskStatus = z.infer<typeof taskStatusSchema>;
export type DocumentTemplate = z.infer<typeof documentTemplateSchema>;
export type OutputLanguage = z.infer<typeof outputLanguageSchema>;
export type TranscriptSegment = z.infer<typeof transcriptSegmentSchema>;
export type CreateCaptureInput = z.infer<typeof createCaptureSchema>;
export type DocumentPayload = z.infer<typeof documentPayloadSchema>;

export interface VideoInfo {
  platform: Platform;
  sourceId: string;
  sourceUrl: string;
  title: string;
  durationMs: number;
}

export interface SubtitleTrack {
  id: string;
  label: string;
  language: string;
  isAutoGenerated: boolean;
}

export interface PlatformAdapter {
  canHandle(url: string): boolean;
  detectVideo(): Promise<VideoInfo>;
  listSubtitleTracks(): Promise<SubtitleTrack[]>;
  readSubtitleTrack(trackId: string): Promise<TranscriptSegment[]>;
  buildTimestampUrl(sourceUrl: string, timeMs: number): string;
}
