import type { SubtitleTrack, TranscriptSegment, VideoInfo } from "@video-to-doc/contracts";

interface YouTubeCaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
}

export interface YouTubePlayerResponse {
  videoDetails?: { videoId?: string; title?: string; lengthSeconds?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: { captionTracks?: YouTubeCaptionTrack[] };
  };
}

export function normalizeYouTubePlayerResponse(value: unknown): YouTubePlayerResponse | null {
  const parsed = typeof value === "string" ? (() => {
    try { return JSON.parse(value) as unknown; } catch { return null; }
  })() : value;
  if (!parsed || typeof parsed !== "object") return null;
  const response = parsed as YouTubePlayerResponse;
  return response.videoDetails ? response : null;
}

export function parseYouTubePlayerResponse(response: YouTubePlayerResponse, sourceUrl: string): {
  video: VideoInfo;
  tracks: SubtitleTrack[];
} {
  const details = response.videoDetails;
  if (!details?.videoId || !details.title || !details.lengthSeconds) {
    throw new Error("YouTube player response is missing video details");
  }
  const durationMs = Number(details.lengthSeconds) * 1_000;
  if (!Number.isFinite(durationMs) || durationMs <= 0) {
    throw new Error("YouTube video duration is invalid");
  }
  const tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return {
    video: {
      platform: "YOUTUBE",
      sourceId: details.videoId,
      sourceUrl,
      title: details.title,
      durationMs,
    },
    tracks: tracks.map((track) => ({
      id: track.baseUrl,
      label: track.name?.simpleText ?? track.name?.runs?.map((run) => run.text ?? "").join("") ?? track.languageCode,
      language: track.languageCode,
      isAutoGenerated: track.kind === "asr",
    })),
  };
}

export function parseYouTubeTimedText(payload: {
  events?: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string }> }>;
}): TranscriptSegment[] {
  return (payload.events ?? []).flatMap((event, sourceIndex) => {
    const text = (event.segs ?? []).map((segment) => segment.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
    const startMs = event.tStartMs ?? 0;
    const durationMs = event.dDurationMs ?? 0;
    if (!text || durationMs <= 0) return [];
    return [{ startMs, endMs: startMs + durationMs, text, sourceIndex }];
  });
}

export function buildYouTubeSubtitleRequestUrls(trackId: string): string[] {
  const original = new URL(trackId);
  const candidates = ["json3", "vtt"].map((format) => {
    const candidate = new URL(original);
    candidate.searchParams.set("fmt", format);
    return candidate.toString();
  });
  candidates.push(original.toString());
  return [...new Set(candidates)];
}

function decodeXmlText(value: string): string {
  return value
    .replace(/<br\s*\/?>/gi, "\n")
    .replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos);/gi, (entity, code: string) => {
      const normalized = code.toLowerCase();
      if (normalized === "amp") return "&";
      if (normalized === "lt") return "<";
      if (normalized === "gt") return ">";
      if (normalized === "quot") return '"';
      if (normalized === "apos") return "'";
      const numeric = normalized.startsWith("#x") ? Number.parseInt(normalized.slice(2), 16) : Number.parseInt(normalized.slice(1), 10);
      return Number.isFinite(numeric) ? String.fromCodePoint(numeric) : entity;
    });
}

function parseCaptionTimestamp(value: string): number {
  const parts = value.trim().split(":").map(Number);
  if (parts.some((part) => !Number.isFinite(part))) return Number.NaN;
  if (parts.length === 2) {
    const minutes = parts[0] ?? Number.NaN;
    const seconds = parts[1] ?? Number.NaN;
    return Math.round((minutes * 60 + seconds) * 1_000);
  }
  if (parts.length === 3) {
    const hours = parts[0] ?? Number.NaN;
    const minutes = parts[1] ?? Number.NaN;
    const seconds = parts[2] ?? Number.NaN;
    return Math.round((hours * 3_600 + minutes * 60 + seconds) * 1_000);
  }
  return Number.NaN;
}

function parseYouTubeXmlCaptions(body: string): TranscriptSegment[] {
  return [...body.matchAll(/<text\b([^>]*)>([\s\S]*?)<\/text>/gi)].flatMap((match, sourceIndex) => {
    const attributes = match[1] ?? "";
    const rawText = match[2] ?? "";
    const start = Number(attributes.match(/\bstart\s*=\s*["']([^"']+)["']/i)?.[1]);
    const duration = Number(attributes.match(/\bdur\s*=\s*["']([^"']+)["']/i)?.[1]);
    const text = decodeXmlText(rawText).replace(/\s+/g, " ").trim();
    if (!text || !Number.isFinite(start) || !Number.isFinite(duration) || duration <= 0) return [];
    const startMs = Math.round(start * 1_000);
    return [{ startMs, endMs: startMs + Math.round(duration * 1_000), text, sourceIndex }];
  });
}

function parseYouTubeVttCaptions(body: string): TranscriptSegment[] {
  const lines = body.replace(/^WEBVTT[^\n]*\n?/i, "").split(/\r?\n/);
  const segments: TranscriptSegment[] = [];
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    const timing = line.match(/^\s*(\S+)\s+-->\s+(\S+)/);
    if (!timing) continue;
    const startMs = parseCaptionTimestamp(timing[1] ?? "");
    const endMs = parseCaptionTimestamp(timing[2] ?? "");
    const textLines: string[] = [];
    for (index += 1; index < lines.length && (lines[index] ?? "").trim(); index += 1) textLines.push((lines[index] ?? "").trim());
    const text = textLines.join(" ").replace(/\s+/g, " ").trim();
    if (text && Number.isFinite(startMs) && Number.isFinite(endMs) && endMs > startMs) segments.push({ startMs, endMs, text, sourceIndex: segments.length });
  }
  return segments;
}

export function parseYouTubeSubtitleResponse(body: string): TranscriptSegment[] {
  const trimmed = body.trim();
  if (!trimmed) return [];
  try {
    const parsed = JSON.parse(trimmed) as { events?: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string }> }> };
    const segments = parseYouTubeTimedText(parsed);
    if (segments.length) return segments;
  } catch {
    // Some caption tracks return XML or WebVTT despite fmt=json3.
  }
  if (/^<\?xml|^<transcript/i.test(trimmed)) return parseYouTubeXmlCaptions(trimmed);
  if (/^WEBVTT/i.test(trimmed)) return parseYouTubeVttCaptions(trimmed);
  return [];
}

export function parseBilibiliSubtitle(payload: {
  body?: Array<{ from?: number; to?: number; content?: string }>;
}): TranscriptSegment[] {
  return (payload.body ?? []).flatMap((item, sourceIndex) => {
    const text = item.content?.replace(/\s+/g, " ").trim() ?? "";
    const startMs = Math.round((item.from ?? 0) * 1_000);
    const endMs = Math.round((item.to ?? 0) * 1_000);
    if (!text || endMs <= startMs) return [];
    return [{ startMs, endMs, text, sourceIndex }];
  });
}

export function parseBilibiliPageData(payload: {
  state?: { videoData?: { bvid?: string; title?: string; duration?: number } };
  playInfo?: {
    data?: {
      subtitle?: {
        subtitles?: Array<{ id?: number; lan?: string; lan_doc?: string; subtitle_url?: string; type?: number }>;
      };
    };
  };
}, sourceUrl: string): { video: VideoInfo; tracks: SubtitleTrack[] } {
  const details = payload.state?.videoData;
  if (!details?.bvid || !details.title || !details.duration) {
    throw new Error("Bilibili page data is missing video details");
  }
  const subtitles = payload.playInfo?.data?.subtitle?.subtitles ?? [];
  return {
    video: {
      platform: "BILIBILI",
      sourceId: details.bvid,
      sourceUrl,
      title: details.title,
      durationMs: Math.round(details.duration * 1_000),
    },
    tracks: subtitles.flatMap((subtitle) => {
      if (!subtitle.subtitle_url || !subtitle.lan) return [];
      const id = subtitle.subtitle_url.startsWith("//") ? `https:${subtitle.subtitle_url}` : subtitle.subtitle_url;
      return [{
        id,
        label: subtitle.lan_doc ?? subtitle.lan,
        language: subtitle.lan,
        isAutoGenerated: subtitle.type === 1,
      }];
    }),
  };
}
