import type { SubtitleTrack, TranscriptSegment, VideoInfo } from "@video-to-doc/contracts";

interface YouTubeCaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string; runs?: Array<{ text?: string }> };
}

interface YouTubePlayerResponse {
  videoDetails?: { videoId?: string; title?: string; lengthSeconds?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: { captionTracks?: YouTubeCaptionTrack[] };
  };
}

export function parseYouTubePlayerResponse(response: YouTubePlayerResponse, sourceUrl: string): {
  video: VideoInfo;
  tracks: SubtitleTrack[];
} {
  const details = response.videoDetails;
  if (!details?.videoId || !details.title || !details.lengthSeconds) {
    throw new Error("YouTube player response is missing video details");
  }
  const durationMs = Number(details.lengthSeconds) * 1_000;
  if (!Number.isFinite(durationMs) || durationMs <= 0) {
    throw new Error("YouTube video duration is invalid");
  }
  const tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return {
    video: {
      platform: "YOUTUBE",
      sourceId: details.videoId,
      sourceUrl,
      title: details.title,
      durationMs,
    },
    tracks: tracks.map((track) => ({
      id: track.baseUrl,
      label: track.name?.simpleText ?? track.name?.runs?.map((run) => run.text ?? "").join("") ?? track.languageCode,
      language: track.languageCode,
      isAutoGenerated: track.kind === "asr",
    })),
  };
}

export function parseYouTubeTimedText(payload: {
  events?: Array<{ tStartMs?: number; dDurationMs?: number; segs?: Array<{ utf8?: string }> }>;
}): TranscriptSegment[] {
  return (payload.events ?? []).flatMap((event, sourceIndex) => {
    const text = (event.segs ?? []).map((segment) => segment.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
    const startMs = event.tStartMs ?? 0;
    const durationMs = event.dDurationMs ?? 0;
    if (!text || durationMs <= 0) return [];
    return [{ startMs, endMs: startMs + durationMs, text, sourceIndex }];
  });
}

export function parseBilibiliSubtitle(payload: {
  body?: Array<{ from?: number; to?: number; content?: string }>;
}): TranscriptSegment[] {
  return (payload.body ?? []).flatMap((item, sourceIndex) => {
    const text = item.content?.replace(/\s+/g, " ").trim() ?? "";
    const startMs = Math.round((item.from ?? 0) * 1_000);
    const endMs = Math.round((item.to ?? 0) * 1_000);
    if (!text || endMs <= startMs) return [];
    return [{ startMs, endMs, text, sourceIndex }];
  });
}

export function parseBilibiliPageData(payload: {
  state?: { videoData?: { bvid?: string; title?: string; duration?: number } };
  playInfo?: {
    data?: {
      subtitle?: {
        subtitles?: Array<{ id?: number; lan?: string; lan_doc?: string; subtitle_url?: string; type?: number }>;
      };
    };
  };
}, sourceUrl: string): { video: VideoInfo; tracks: SubtitleTrack[] } {
  const details = payload.state?.videoData;
  if (!details?.bvid || !details.title || !details.duration) {
    throw new Error("Bilibili page data is missing video details");
  }
  const subtitles = payload.playInfo?.data?.subtitle?.subtitles ?? [];
  return {
    video: {
      platform: "BILIBILI",
      sourceId: details.bvid,
      sourceUrl,
      title: details.title,
      durationMs: Math.round(details.duration * 1_000),
    },
    tracks: subtitles.flatMap((subtitle) => {
      if (!subtitle.subtitle_url || !subtitle.lan) return [];
      const id = subtitle.subtitle_url.startsWith("//") ? `https:${subtitle.subtitle_url}` : subtitle.subtitle_url;
      return [{
        id,
        label: subtitle.lan_doc ?? subtitle.lan,
        language: subtitle.lan,
        isAutoGenerated: subtitle.type === 1,
      }];
    }),
  };
}
